services:
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db
  web:
    build: .
    # Correção para o comando:
    # 1. Usar o formato "exec" (lista de strings) é mais robusto.
    # 2. Especificar o caminho completo para 'python' (/usr/local/bin/python)
    #    garante que o Docker o encontre dentro do contêiner.
    command: ["/opt/pysetup/.venv/bin/python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      # A montagem do volume deve corresponder ao WORKDIR do Dockerfile para maior clareza.
      # O Dockerfile usa WORKDIR /app, então montamos o diretório local para /app.
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - db

volumes:
  postgres_data:
